name: 🐞 Issue
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Course
    description: Which course are you reporting an issue with?
    multiple: false
    options:
      - IBM Public Cloud Fundamentals Level 1
      - IBM Cloud Satellite Level 2 
      - IBM Cloud Satellite for Sales Level 3 
      - IBM Cloud Satellite for Technical Sales Level 3
      - IBM Cloud for Financial Services Level 2 (V2)
      - SAP on IBM Cloud Level 2
      - SAP on IBM Power Virtual Server for Technical Sales Level 3
      - IBM Cloud for VMware Solutions Level 2 
      - IBM Cloud for VMware Solutions for Sales Level 3 
      - IBM Cloud for VMware Solutions for Technical Sales Level 3
      - IBM Power Systems Virtual Server Level 2 
      - IBM Power Systems Virtual Server for Sales Level 3 
      - IBM Power Systems Virtual Server for Technical Sales Level 3
      - IBM Cloud Object Storage (for Cloud Sellers) Level 2 
      - IBM Cloud Object Storage for Sales Level 3 
      - IBM Cloud Object Storage for Technical Sales Level 3
  validations:
    required: true 
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
  validations:
    required: false
